name: 'action-add-to-catalog'
description: 'Adds an entry to the catalog index'
author: 'Cloud Native Toolkit'
inputs:
  catalogFile:
    required: true
    description: 'The yaml file where the catalog information is stored'
    default: 'catalog.yaml'
  category:
    required: true
    description: 'The category of the module'
  name:
    required: true
    description: 'The name of the module in the catalog'
  displayName:
    required: false
    description: 'The display name of the module in the catalog'
  id:
    required: false
    description: 'The source id of the module (e.g. the git repo slug)'
  repoUrl:
    required: false
    description: 'The url of the repository'
  group:
    required: false
    description: 'The group the module is part of'
  cloudProvider:
    required: false
    description: 'The cloud provider, if applicable, for the module. (E.g. ibm, aws, azure)'
  softwareProvider:
    required: false
    description: 'The provider of the software that will be installed into a cluster, if applicable. (E.g. ibm-cp)'
runs:
  using: 'node16'
  main: 'dist/index.js'
